apiVersion: v1
kind: Pod
metadata:
  name: poc-pod
  labels:
    name: mainpage
    type: frontend
spec:
  containers:
    - name: myapp
      image: nginxdemos/hello
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
