apiVersion: v1
kind: Service
metadata:
  name: service-poc
spec:
  type: NodePort
  kind: Service
  apiVersion: v1
  metadata:
    name: Service Name
  spec:
    selector: { name: mainpage, type: frontend }
    type: LoadBalancer | ClusterIP | NodePort
    ports: [{ port: 80, targetPort: 80, nodePort: 30008 }]
